sudo: false
language: ruby
cache: bundler
services:
  - postgresql
rvm:
  - 2.4.4
before_install: gem install bundler -v 1.16.1
before_script:
  - psql -c 'create database minesweeper_test;' -U postgres
